-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  role text,
  full_name text,
  employee_id text UNIQUE,
  jobtitles text,
  status text DEFAULT 'Active'::text,
  start_date date,
  probation_date date,
  termination_date date,
  nickname text,
  avatar_color text CHECK (avatar_color IS NULL OR avatar_color ~ '^#[0-9a-fA-F]{6}$'::text),
  avatar_initials text CHECK (avatar_initials IS NULL OR char_length(avatar_initials) >= 1 AND char_length(avatar_initials) <= 2),
  avatar_url text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.login_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  action text DEFAULT 'login'::text,
  CONSTRAINT login_activity_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  prompt text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_prompts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  feature text NOT NULL,
  action text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'error'::text, 'warning'::text])),
  input jsonb,
  result_count integer,
  duration_ms integer,
  folder_id text,
  saved_file_name text,
  error_message text,
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_feature_access (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  feature text NOT NULL,
  granted_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_feature_access_pkey PRIMARY KEY (id),
  CONSTRAINT user_feature_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_feature_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kol_tracker (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  size text,
  platform text,
  rate text,
  contact text,
  note text,
  added_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT kol_tracker_pkey PRIMARY KEY (id),
  CONSTRAINT kol_tracker_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kol_deals_influencer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel text NOT NULL DEFAULT ''::text,
  kol text DEFAULT ''::text,
  fullname text DEFAULT ''::text,
  size text DEFAULT ''::text,
  platform text DEFAULT ''::text,
  phase text DEFAULT 'presale'::text,
  owner_role text DEFAULT ''::text,
  owner_name text DEFAULT ''::text,
  billing_value text DEFAULT ''::text,
  kol_budget text DEFAULT ''::text,
  ad_budget text DEFAULT ''::text,
  balance text DEFAULT ''::text,
  checkin date,
  post_date date,
  asset_link text DEFAULT ''::text,
  doc_link text DEFAULT ''::text,
  link_post text DEFAULT ''::text,
  note text DEFAULT ''::text,
  voucher text DEFAULT ''::text,
  status text DEFAULT ''::text,
  report text DEFAULT ''::text,
  kol_id_card text DEFAULT ''::text,
  kol_phone text DEFAULT ''::text,
  kol_email text DEFAULT ''::text,
  kol_address text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  service_type text DEFAULT 'kol'::text,
  created_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT kol_deals_influencer_pkey PRIMARY KEY (id),
  CONSTRAINT kol_deals_influencer_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kol_deals_production (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel text NOT NULL DEFAULT ''::text,
  fullname text DEFAULT ''::text,
  photographer text DEFAULT ''::text,
  photo_package text DEFAULT ''::text,
  deliverable text DEFAULT ''::text,
  phase text DEFAULT 'presale'::text,
  owner_role text DEFAULT ''::text,
  owner_name text DEFAULT ''::text,
  billing_value text DEFAULT ''::text,
  balance text DEFAULT ''::text,
  travel_cost text DEFAULT ''::text,
  accom_cost text DEFAULT ''::text,
  checkin date,
  post_date date,
  asset_link text DEFAULT ''::text,
  doc_link text DEFAULT ''::text,
  link_post text DEFAULT ''::text,
  note text DEFAULT ''::text,
  voucher text DEFAULT ''::text,
  status text DEFAULT ''::text,
  report text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  service_type text DEFAULT 'photo'::text,
  created_by uuid,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT kol_deals_production_pkey PRIMARY KEY (id),
  CONSTRAINT kol_deals_production_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.ads_allpage (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  account_name text NOT NULL,
  account_id text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_allpage_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_rawdata (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  account_name text,
  account_id text,
  campaign_name text,
  campaign_id text,
  adset_name text,
  adset_id text,
  ad_name text,
  ad_id text,
  date_start date,
  date_stop date,
  impressions numeric DEFAULT 0,
  inline_link_clicks numeric DEFAULT 0,
  unique_inline_link_clicks numeric DEFAULT 0,
  reach numeric DEFAULT 0,
  spend numeric DEFAULT 0,
  purchases numeric DEFAULT 0,
  purchase_value numeric DEFAULT 0,
  leads numeric DEFAULT 0,
  messaging_conversations_started numeric DEFAULT 0,
  post_shares numeric DEFAULT 0,
  page_likes numeric DEFAULT 0,
  cpc numeric DEFAULT 0,
  ctr numeric DEFAULT 0,
  cpm numeric DEFAULT 0,
  frequency numeric DEFAULT 0,
  clicks_all numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  objective text,
  ctr_all numeric DEFAULT 0,
  roas numeric DEFAULT 0,
  cost_per_result numeric DEFAULT 0,
  video_views_3s numeric DEFAULT 0,
  video_p25 numeric DEFAULT 0,
  video_p50 numeric DEFAULT 0,
  video_p75 numeric DEFAULT 0,
  video_p100 numeric DEFAULT 0,
  video_avg_time numeric DEFAULT 0,
  hook_rate numeric DEFAULT 0,
  hold_rate numeric DEFAULT 0,
  post_comments numeric DEFAULT 0,
  post_reactions numeric DEFAULT 0,
  cost_per_engagement numeric DEFAULT 0,
  cost_per_like numeric DEFAULT 0,
  cost_per_message numeric DEFAULT 0,
  post_engagement numeric DEFAULT 0,
  CONSTRAINT ads_rawdata_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text,
  role text NOT NULL DEFAULT 'user'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_user_page_permissions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  account_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_user_page_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT ads_user_page_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.ads_users(id),
  CONSTRAINT ads_user_page_permissions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.ads_allpage(account_id)
);
CREATE TABLE public.ads_campaign_highlights (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  campaign_name text NOT NULL,
  metric_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_campaign_highlights_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_geo (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ad_id text,
  date_start date,
  region text,
  impressions numeric DEFAULT 0,
  clicks numeric DEFAULT 0,
  clicks_all numeric DEFAULT 0,
  spend numeric DEFAULT 0,
  reach numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ad_name text,
  date_stop date,
  inline_link_clicks numeric DEFAULT 0,
  purchases numeric DEFAULT 0,
  purchase_value numeric DEFAULT 0,
  CONSTRAINT ads_geo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_demographic (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ad_id text,
  date_start date,
  age text,
  gender text,
  impressions numeric DEFAULT 0,
  clicks numeric DEFAULT 0,
  clicks_all numeric DEFAULT 0,
  spend numeric DEFAULT 0,
  reach numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ad_name text,
  date_stop date,
  inline_link_clicks numeric DEFAULT 0,
  purchases numeric DEFAULT 0,
  purchase_value numeric DEFAULT 0,
  CONSTRAINT ads_demographic_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_device (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ad_id text,
  date_start date,
  impression_device text,
  impressions numeric DEFAULT 0,
  clicks numeric DEFAULT 0,
  clicks_all numeric DEFAULT 0,
  spend numeric DEFAULT 0,
  reach numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ad_name text,
  date_stop date,
  inline_link_clicks numeric DEFAULT 0,
  purchases numeric DEFAULT 0,
  purchase_value numeric DEFAULT 0,
  CONSTRAINT ads_device_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ota_file_headers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ota text NOT NULL UNIQUE,
  headers ARRAY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ota_file_headers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_lead_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  city text NOT NULL UNIQUE,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::hotel_lead_queue_status,
  scraped_count integer NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  uploaded_by text,
  started_at timestamp with time zone,
  province text,
  CONSTRAINT hotel_lead_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  queue_id uuid,
  city text NOT NULL,
  source_type text NOT NULL,
  place_id text NOT NULL UNIQUE,
  name text NOT NULL,
  phone text,
  email text,
  website text,
  address text,
  rating numeric,
  reviews_count integer,
  google_maps_link text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  hotel_id text UNIQUE,
  province text,
  classifier_category text,
  classifier_brand text,
  classifier_confidence text,
  classifier_reason text,
  is_blacklisted boolean DEFAULT false,
  manually_approved boolean DEFAULT false,
  is_claimed boolean,
  photos_count integer,
  pipedrive_imported boolean NOT NULL DEFAULT false,
  CONSTRAINT hotel_leads_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_leads_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.hotel_lead_queue(id)
);
CREATE TABLE public.scrape_queue_serp (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel_name text NOT NULL,
  city text NOT NULL,
  province text,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  sheet_row_index integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'done'::text, 'error'::text, 'not_found'::text])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scrape_queue_serp_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_email_domain_blacklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  domain text NOT NULL UNIQUE,
  category text NOT NULL,
  brand_or_company text,
  confidence text NOT NULL,
  reason text,
  auto_detected boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hotel_email_domain_blacklist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fb_token_store (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  access_token text NOT NULL,
  expires_at timestamp with time zone,
  refreshed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fb_token_store_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leadfinder_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action text NOT NULL,
  tab text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leadfinder_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT LeadFinder_activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.meeting_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp without time zone DEFAULT now(),
  meeting_date date,
  hotel_name text,
  meeting_type text,
  bd_employee text,
  s1_score integer,
  s2_score integer,
  s3_score integer,
  s4_score integer,
  s5_score integer,
  s6_score integer,
  s7_score integer,
  s8_score integer,
  total_score integer,
  raw_json jsonb,
  flags text,
  drive_link text,
  report_url text,
  report_file text,
  duration_min integer,
  bd_talk_pct numeric,
  customer_talk_pct numeric,
  CONSTRAINT meeting_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meeting_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  flag_text text,
  severity text,
  CONSTRAINT meeting_flags_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_flags_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.meeting_reports(id)
);
CREATE TABLE public.meeting_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  name text,
  role text,
  engagement text,
  CONSTRAINT meeting_participants_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_participants_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.meeting_reports(id)
);
CREATE TABLE public.orm_shoprate_hotels (
  id integer NOT NULL DEFAULT nextval('orm_shoprate_hotels_id_seq'::regclass),
  hotel_name text NOT NULL,
  city text DEFAULT 'Bangkok'::text,
  type text NOT NULL CHECK (type = ANY (ARRAY['ours'::text, 'comp'::text])),
  google_hotel_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  parent_id integer,
  created_by text,
  owner_user_id uuid,
  CONSTRAINT orm_shoprate_hotels_pkey PRIMARY KEY (id),
  CONSTRAINT orm_shoprate_hotels_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id),
  CONSTRAINT orm_shoprate_hotels_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.orm_shoprate_hotels(id)
);
CREATE TABLE public.orm_shoprate_history (
  id integer NOT NULL DEFAULT nextval('orm_shoprate_history_id_seq'::regclass),
  run_id uuid NOT NULL,
  hotel_id integer,
  hotel_name text NOT NULL,
  period_type text NOT NULL CHECK (period_type = ANY (ARRAY['3-day'::text, '14-day'::text, '30-day'::text, '60-day'::text, 'holiday'::text])),
  day_type text NOT NULL CHECK (day_type = ANY (ARRAY['WD'::text, 'WE'::text, 'LH'::text])),
  stay_date date NOT NULL,
  check_in date NOT NULL,
  check_out date NOT NULL,
  is_alt_date boolean NOT NULL DEFAULT false,
  alt_date_offset integer DEFAULT 0,
  price_booking numeric,
  price_agoda numeric,
  price_expedia numeric,
  price_tripcom numeric,
  price_traveloka numeric,
  price_tiketcom numeric,
  floor_rate numeric,
  cheapest_ota text,
  variance_pct numeric,
  official_vs_ota numeric,
  scraped_at timestamp with time zone NOT NULL DEFAULT now(),
  holiday_name text,
  price_official numeric,
  hotel_link text,
  status text,
  CONSTRAINT orm_shoprate_history_pkey PRIMARY KEY (id),
  CONSTRAINT orm_shoprate_history_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.orm_shoprate_hotels(id)
);
CREATE TABLE public.orm_shoprate_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel_id integer,
  hotel_name text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  status text NOT NULL DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'done'::text, 'failed'::text])),
  week_label text NOT NULL,
  triggered_by text,
  rows_saved integer DEFAULT 0,
  notes text,
  CONSTRAINT orm_shoprate_runs_pkey PRIMARY KEY (id),
  CONSTRAINT orm_shoprate_runs_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.orm_shoprate_hotels(id)
);
CREATE TABLE public.news_letter_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  user_email text,
  action text NOT NULL,
  field_name text,
  old_value text,
  new_value text,
  hotel_name text,
  spreadsheet_id text,
  row_index integer,
  province text,
  city text,
  hotels_sent jsonb,
  hotels_count integer,
  CONSTRAINT news_letter_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT news_letter_activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_reports (
  token uuid NOT NULL DEFAULT gen_random_uuid(),
  record_json jsonb NOT NULL,
  hotel_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_reports_pkey PRIMARY KEY (token)
);
CREATE TABLE public.scraper_api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  api_key text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scraper_api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scraper_api_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_key_id uuid,
  url_requested text NOT NULL,
  platform text,
  status text,
  error_message text,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  company_name text,
  search_parameters jsonb,
  json_response jsonb,
  final_url text,
  CONSTRAINT scraper_api_requests_pkey PRIMARY KEY (id),
  CONSTRAINT scraper_api_requests_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.scraper_api_keys(id)
);
CREATE TABLE public.processing_jobs (
  id text NOT NULL,
  kind text NOT NULL,
  file_name text NOT NULL,
  status text NOT NULL,
  drive_link text,
  report_file text,
  total_score numeric,
  assembly_cost_usd numeric,
  analysis_cost_usd numeric,
  cost_usd numeric,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source text,
  CONSTRAINT processing_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orm_team (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  employee_id uuid,
  joined_at date,
  left_at date,
  CONSTRAINT orm_team_pkey PRIMARY KEY (id),
  CONSTRAINT orm_team_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.hotel_profiles (
  client_hotel_id text NOT NULL,
  client_hotel_name text NOT NULL,
  team_name text,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  assigned_at date,
  status text NOT NULL DEFAULT 'Active'::text,
  service text,
  survey_score numeric,
  payment_grade integer NOT NULL DEFAULT 100 CHECK (payment_grade >= 0 AND payment_grade <= 100),
  tier text,
  contract_persons jsonb NOT NULL DEFAULT '[]'::jsonb,
  overdue_months integer NOT NULL DEFAULT 0 CHECK (overdue_months >= 0),
  late_payments_12m integer NOT NULL DEFAULT 0 CHECK (late_payments_12m >= 0),
  customer_id uuid,
  payment_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  invoice_legacy_process boolean NOT NULL DEFAULT false,
  CONSTRAINT hotel_profiles_pkey PRIMARY KEY (client_hotel_id),
  CONSTRAINT hotel_profiles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_master(id)
);
CREATE TABLE public.hotel_monthly_report (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  period date NOT NULL,
  h_comm numeric,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text,
  revenue numeric,
  discount numeric,
  discount_reason text,
  target numeric,
  adr numeric,
  room_night integer,
  room_night_target numeric,
  adr_target numeric,
  source text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT hotel_monthly_report_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_commission_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id)
);
CREATE TABLE public.hotel_team_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text,
  team_name text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  CONSTRAINT hotel_team_history_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_team_history_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id)
);
CREATE TABLE public.orm_funding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  record_date date NOT NULL,
  client_hotel_id text NOT NULL,
  ota_name text NOT NULL,
  booking_id text NOT NULL,
  checkin_date date,
  case_type text NOT NULL,
  case_detail text,
  correct_amount numeric NOT NULL,
  wrong_amount numeric NOT NULL,
  compensation numeric NOT NULL,
  account_team jsonb NOT NULL DEFAULT '[]'::jsonb,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text,
  approved_role text,
  approved_by text,
  approved_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_hotel_name text,
  approvals jsonb NOT NULL DEFAULT '[]'::jsonb,
  settlement_type text,
  settled_period date,
  settled_at timestamp with time zone,
  settled_by text,
  CONSTRAINT orm_funding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orm_team_meta (
  team_name text NOT NULL,
  color text,
  icon text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orm_team_meta_pkey PRIMARY KEY (team_name)
);
CREATE TABLE public.orm_shoprate_hotel_comps (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  main_hotel_id bigint NOT NULL,
  comp_hotel_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orm_shoprate_hotel_comps_pkey PRIMARY KEY (id),
  CONSTRAINT orm_shoprate_hotel_comps_main_hotel_id_fkey FOREIGN KEY (main_hotel_id) REFERENCES public.orm_shoprate_hotels(id),
  CONSTRAINT orm_shoprate_hotel_comps_comp_hotel_id_fkey FOREIGN KEY (comp_hotel_id) REFERENCES public.orm_shoprate_hotels(id)
);
CREATE TABLE public.production_report_sends (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_id text NOT NULL,
  sheet_no text,
  hotel_name text,
  period text,
  email_to text,
  sent_by text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'sent'::text,
  error_message text,
  CONSTRAINT production_report_sends_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_orm_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  registration text,
  rooms integer,
  contract_start date,
  contract_end date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text,
  system text,
  service text,
  survey_score numeric,
  payment_grade integer CHECK (payment_grade >= 0 AND payment_grade <= 100),
  tier text,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason text,
  ps_offers jsonb NOT NULL DEFAULT '[]'::jsonb,
  client_hotel_name text,
  overdue_months integer CHECK (overdue_months >= 0),
  late_payments_12m integer CHECK (late_payments_12m >= 0),
  service_form text,
  guarantee boolean NOT NULL DEFAULT false,
  guarantee_amount numeric,
  terminate_reason_code text,
  service_start date,
  sku_id text,
  CONSTRAINT hotel_orm_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_contracts_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT hotel_orm_contracts_sku_fk FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.orm_shoprate_verifies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel_name text NOT NULL,
  city text,
  scraped_at timestamp with time zone NOT NULL DEFAULT now(),
  triggered_by text,
  status text DEFAULT 'success'::text,
  CONSTRAINT orm_shoprate_verifies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_report_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  period date NOT NULL,
  action text NOT NULL,
  field text NOT NULL,
  old_value text,
  new_value text,
  source text,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotel_report_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ps_snapshot_email_template (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  content text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by text,
  CONSTRAINT ps_snapshot_email_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ps_snapshot_sends (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text,
  hotel_name text NOT NULL,
  email_to text,
  period text NOT NULL,
  sent_by text,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  error_message text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ps_snapshot_sends_pkey PRIMARY KEY (id),
  CONSTRAINT ps_snapshot_sends_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id)
);
CREATE TABLE public.ads_portfolio_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  metric text NOT NULL,
  direction text NOT NULL DEFAULT 'higher_better'::text CHECK (direction = ANY (ARRAY['higher_better'::text, 'lower_better'::text])),
  target numeric,
  green_min numeric,
  yellow_min numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  green_op text NOT NULL DEFAULT '>='::text CHECK (green_op = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text])),
  yellow_op text NOT NULL DEFAULT '>='::text CHECK (yellow_op = ANY (ARRAY['<'::text, '<='::text, '>'::text, '>='::text])),
  campaign_filter text,
  CONSTRAINT ads_portfolio_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_portfolio_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_portfolio_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ads_portfolio_profile_accounts (
  profile_id uuid NOT NULL,
  account_id text NOT NULL,
  CONSTRAINT ads_portfolio_profile_accounts_pkey PRIMARY KEY (profile_id, account_id),
  CONSTRAINT ads_portfolio_profile_accounts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.ads_portfolio_profiles(id),
  CONSTRAINT ads_portfolio_profile_accounts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.ads_allpage(account_id)
);
CREATE TABLE public.hipps_analyses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hotel_name text NOT NULL,
  status text NOT NULL DEFAULT 'running'::text,
  overall_result jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hipps_analyses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hipps_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  analysis_id uuid NOT NULL,
  module_name text NOT NULL,
  status text NOT NULL DEFAULT 'running'::text,
  log_text text,
  result_data jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hipps_logs_pkey PRIMARY KEY (id),
  CONSTRAINT hipps_logs_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.hipps_analyses(id)
);
CREATE TABLE public.hotel_member_assignment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  employee_id uuid NOT NULL,
  start_period date NOT NULL,
  end_period date,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotel_member_assignment_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_member_assignment_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT hotel_member_assignment_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ps_syncup_sends (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  client_hotel_id text NOT NULL,
  hotel_name text NOT NULL,
  email_to text,
  period text NOT NULL,
  template_type text NOT NULL CHECK (template_type = ANY (ARRAY['ads'::text, 'content_only'::text])),
  sent_by text,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  error_message text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ps_syncup_sends_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bc_bonus_monthly (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  period date NOT NULL,
  net numeric NOT NULL,
  net_ytd numeric NOT NULL,
  breakdown jsonb,
  locked_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_by uuid,
  CONSTRAINT bc_bonus_monthly_pkey PRIMARY KEY (id),
  CONSTRAINT bc_bonus_monthly_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id),
  CONSTRAINT bc_bonus_monthly_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hipps_hotels (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hotel_name text NOT NULL,
  location text,
  property_token text,
  google_hotel_url text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_ours boolean DEFAULT true,
  CONSTRAINT hipps_hotels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hipps_hotel_competitors (
  hotel_id uuid NOT NULL,
  competitor_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hipps_hotel_competitors_pkey PRIMARY KEY (hotel_id, competitor_id),
  CONSTRAINT hipps_hotel_competitors_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hipps_hotels(id),
  CONSTRAINT hipps_hotel_competitors_competitor_id_fkey FOREIGN KEY (competitor_id) REFERENCES public.hipps_hotels(id)
);
CREATE TABLE public.hotel_monthly_report_paystatus_backup_20260728 (
  id uuid,
  client_hotel_id text,
  period date,
  payment_status text
);
CREATE TABLE public.hotel_orm_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_start date,
  period_end date,
  model text,
  monthly_fee numeric,
  comm_pct numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sku text,
  guarantee_amount numeric,
  CONSTRAINT hotel_orm_periods_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_orm_periods_sku_fk FOREIGN KEY (sku) REFERENCES public.product_catalog_service(sku),
  CONSTRAINT hotel_orm_periods_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_orm_contracts(id)
);
CREATE TABLE public.hotel_marcom_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  service_form text,
  contract_start date,
  contract_end date,
  ps_offers jsonb NOT NULL DEFAULT '[]'::jsonb,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason_code text,
  terminate_reason text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rooms integer,
  system text,
  service_start date,
  sku_id text,
  CONSTRAINT hotel_marcom_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_marcom_contracts_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT hotel_marcom_contracts_sku_fk FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_marcom_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_start date,
  period_end date,
  platforms ARRAY NOT NULL DEFAULT '{}'::text[],
  rate_amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sku text,
  note text,
  CONSTRAINT hotel_marcom_periods_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_marcom_periods_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_marcom_contracts(id),
  CONSTRAINT hotel_marcom_periods_sku_fk FOREIGN KEY (sku) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_marcom_upsells (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  item text NOT NULL,
  service_type text,
  start_date date,
  end_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotel_marcom_upsells_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_marcom_upsells_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_marcom_contracts(id)
);
CREATE TABLE public.hotel_prod_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  service_form text,
  contract_start date,
  contract_end date,
  ps_offers jsonb NOT NULL DEFAULT '[]'::jsonb,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason_code text,
  terminate_reason text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rooms integer,
  system text,
  service_start date,
  sku_id text,
  service_line text CHECK (service_line IS NULL OR (service_line = ANY (ARRAY['ORM'::text, 'MARCOM'::text, 'PRO'::text, 'PP'::text]))),
  CONSTRAINT hotel_prod_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_prod_contracts_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT hotel_prod_contracts_sku_fk FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_prod_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_start date,
  period_end date,
  items ARRAY NOT NULL DEFAULT '{}'::text[],
  rate_amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  CONSTRAINT hotel_prod_periods_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_prod_periods_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_prod_contracts(id)
);
CREATE TABLE public.hotel_profiles_backup_20260807 (
  client_hotel_id text,
  client_hotel_name text,
  team_name text,
  model text,
  contract_start date,
  contract_end date,
  created_at timestamp with time zone,
  created_by text,
  assigned_at date,
  registration text,
  status text,
  rooms integer,
  system text,
  service text,
  monthly_fee numeric,
  comm_pct numeric,
  survey_score numeric,
  payment_grade integer,
  tier text,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason text,
  contract_persons jsonb,
  ps_offers jsonb,
  overdue_months integer,
  late_payments_12m integer
);
CREATE TABLE public.hotel_profiles_contract_persons_backup_20260807 (
  client_hotel_id text,
  contract_persons jsonb,
  backed_up_at timestamp with time zone
);
CREATE TABLE public.crm_boards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  accent_color text NOT NULL DEFAULT '#1e3a8a'::text,
  card_prefix text NOT NULL DEFAULT 'CARD'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_boards_pkey PRIMARY KEY (id),
  CONSTRAINT crm_boards_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_board_columns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  board_id uuid NOT NULL,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#64748b'::text,
  position integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_board_columns_pkey PRIMARY KEY (id),
  CONSTRAINT crm_board_columns_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.crm_boards(id)
);
CREATE TABLE public.crm_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  board_id uuid NOT NULL,
  column_id uuid NOT NULL,
  seq integer NOT NULL,
  title text NOT NULL,
  amount numeric,
  due_date date,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  assignee_id uuid,
  position integer NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  checklist_label text NOT NULL DEFAULT 'เช็คลิสต์'::text,
  description text,
  CONSTRAINT crm_cards_pkey PRIMARY KEY (id),
  CONSTRAINT crm_cards_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.crm_boards(id),
  CONSTRAINT crm_cards_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.crm_board_columns(id),
  CONSTRAINT crm_cards_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.profiles(id),
  CONSTRAINT crm_cards_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_board_stars (
  board_id uuid NOT NULL,
  user_id uuid NOT NULL,
  CONSTRAINT crm_board_stars_pkey PRIMARY KEY (board_id, user_id),
  CONSTRAINT crm_board_stars_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.crm_boards(id),
  CONSTRAINT crm_board_stars_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_card_checklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  card_id uuid NOT NULL,
  label text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_card_checklist_pkey PRIMARY KEY (id),
  CONSTRAINT crm_card_checklist_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.crm_cards(id)
);
CREATE TABLE public.crm_card_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  card_id uuid NOT NULL,
  author_id uuid,
  body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_card_comments_pkey PRIMARY KEY (id),
  CONSTRAINT crm_card_comments_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.crm_cards(id),
  CONSTRAINT crm_card_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_card_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  card_id uuid NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size bigint,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_card_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT crm_card_attachments_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.crm_cards(id),
  CONSTRAINT crm_card_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_labels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  board_id uuid NOT NULL,
  name text NOT NULL,
  color text NOT NULL,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_labels_pkey PRIMARY KEY (id),
  CONSTRAINT crm_labels_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.crm_boards(id)
);
CREATE TABLE public.crm_card_labels (
  card_id uuid NOT NULL,
  label_id uuid NOT NULL,
  CONSTRAINT crm_card_labels_pkey PRIMARY KEY (card_id, label_id),
  CONSTRAINT crm_card_labels_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.crm_cards(id),
  CONSTRAINT crm_card_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES public.crm_labels(id)
);
CREATE TABLE public.calc_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scope text NOT NULL DEFAULT 'orm'::text,
  version integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  config jsonb NOT NULL,
  note text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT calc_config_pkey PRIMARY KEY (id),
  CONSTRAINT calc_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.product_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sku_id text NOT NULL UNIQUE,
  product_name text NOT NULL,
  line_category text NOT NULL CHECK (line_category = ANY (ARRAY['ORM/setup'::text, 'ORM/onetime'::text, 'ORM/monthly'::text, 'ORM/addon'::text, 'MARCOM/setup'::text, 'MARCOM/onetime'::text, 'MARCOM/monthly'::text, 'MARCOM/addon'::text, 'PRO/per_use'::text, 'PP/per_use'::text])),
  billing_model text CHECK (billing_model = ANY (ARRAY['Onetime'::text, 'Per_use'::text, 'Flat_rate'::text, 'Monthly'::text, 'Commission'::text])),
  price integer,
  p_comm numeric,
  condition text,
  status text NOT NULL DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Active'::text, 'Inactive'::text, 'Draft'::text])),
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  parent_sku text,
  max_quantity integer,
  CONSTRAINT product_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT product_catalog_parent_fk FOREIGN KEY (parent_sku) REFERENCES public.product_catalog(sku_id)
);
CREATE TABLE public.customer_master (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_id text,
  branch_code text NOT NULL DEFAULT '00000'::text,
  registered_name text NOT NULL,
  registration_type text NOT NULL CHECK (registration_type = ANY (ARRAY['Personal'::text, 'Corporate'::text])),
  address text,
  zip_code text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hotel_orm_contract_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_id uuid,
  sku_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotel_orm_contract_items_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_orm_contract_items_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_orm_contracts(id),
  CONSTRAINT hotel_orm_contract_items_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.hotel_orm_periods(id),
  CONSTRAINT hotel_orm_contract_items_sku_fk FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.product_catalog_service (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sku text NOT NULL UNIQUE,
  product_name text,
  service_line text NOT NULL CHECK (service_line = ANY (ARRAY['ORM'::text, 'MARCOM'::text, 'PROD'::text, 'PP'::text])),
  category text NOT NULL CHECK (category = ANY (ARRAY['setup'::text, 'monthly'::text, 'per_use'::text, 'addon'::text])),
  billing text NOT NULL CHECK (billing = ANY (ARRAY['one_time'::text, 'monthly'::text, 'per_use'::text])),
  pricing_model text NOT NULL CHECK (pricing_model = ANY (ARRAY['fixed'::text, 'commission_only'::text, 'fixed_plus_commission'::text, 'tbd'::text])),
  tier_group text CHECK (tier_group = ANY (ARRAY['ORM'::text, 'META'::text, 'TIKTOK'::text])),
  pricing_option_group text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text])),
  base_price integer,
  commission_rate numeric,
  pricing_confirmed_at timestamp with time zone,
  pricing_confirmed_by text,
  parent_sku text,
  max_quantity integer,
  bundle_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  guarantee_amount integer,
  description text,
  condition text,
  CONSTRAINT product_catalog_service_pkey PRIMARY KEY (id),
  CONSTRAINT product_catalog_service_parent_sku_fkey FOREIGN KEY (parent_sku) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_marcom_contract_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_id uuid,
  sku_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hotel_marcom_contract_items_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_marcom_contract_items_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_marcom_contracts(id),
  CONSTRAINT hotel_marcom_contract_items_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.hotel_marcom_periods(id),
  CONSTRAINT hotel_marcom_contract_items_sku_id_fkey FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_project_planning_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_hotel_id text NOT NULL,
  service_form text,
  contract_start date,
  contract_end date,
  ps_offers jsonb NOT NULL DEFAULT '[]'::jsonb,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason_code text,
  terminate_reason text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rooms integer,
  system text,
  service_start date,
  sku_id text,
  service_line text CHECK (service_line IS NULL OR (service_line = ANY (ARRAY['ORM'::text, 'MARCOM'::text, 'PRO'::text, 'PP'::text]))),
  CONSTRAINT hotel_project_planning_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_project_planning_contracts_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT hotel_project_planning_contracts_sku_fk FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.hotel_project_planning_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  period_start date,
  period_end date,
  items ARRAY NOT NULL DEFAULT '{}'::text[],
  rate_amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  CONSTRAINT hotel_project_planning_periods_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_project_planning_periods_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_project_planning_contracts(id)
);
CREATE TABLE public.hotel_orm_contracts_backup_20260902 (
  id uuid,
  client_hotel_id text,
  model text,
  registration text,
  rooms integer,
  contract_start date,
  contract_end date,
  created_at timestamp with time zone,
  created_by text,
  system text,
  service text,
  monthly_fee numeric,
  comm_pct numeric,
  survey_score numeric,
  payment_grade integer,
  tier text,
  terminate_date date,
  terminate_fee numeric,
  terminate_reason text,
  ps_offers jsonb,
  client_hotel_name text,
  overdue_months integer,
  late_payments_12m integer,
  service_form text,
  guarantee boolean,
  guarantee_amount numeric,
  terminate_reason_code text,
  service_start date,
  sku_id text
);
CREATE TABLE public.hotel_orm_periods_backup_20260902 (
  id uuid,
  contract_id uuid,
  period_start date,
  period_end date,
  model text,
  monthly_fee numeric,
  comm_pct numeric,
  created_at timestamp with time zone
);
CREATE TABLE public.hotel_orm_contract_items_backup_20260902 (
  id uuid,
  contract_id uuid,
  period_id uuid,
  sku_id text,
  quantity integer,
  created_at timestamp with time zone
);
CREATE TABLE public.hotel_marcom_periods_backup_20260902 (
  id uuid,
  contract_id uuid,
  period_start date,
  period_end date,
  platforms ARRAY,
  rate_amount numeric,
  created_at timestamp with time zone,
  comm_pct numeric,
  sku text,
  note text
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_no text NOT NULL UNIQUE,
  hotel_name text NOT NULL,
  contact_name text,
  contact_phone text,
  contact_email text,
  customer_id uuid,
  crm_card_id uuid,
  has_existing_ota boolean,
  ota_channels ARRAY,
  ota_share_percent numeric,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'declined'::text, 'contract_in_progress'::text, 'contract_generated'::text])),
  accepted_sku text,
  inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
  pdf_path text,
  pdf_size integer,
  note text,
  prepared_by text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  decided_at timestamp with time zone,
  deal_id text,
  run_no integer,
  product_name text,
  service_line text CHECK (service_line IS NULL OR (service_line = ANY (ARRAY['ORM'::text, 'MARCOM'::text, 'PROD'::text, 'PP'::text]))),
  skus ARRAY,
  root_quote_id uuid,
  parent_quote_id uuid,
  rev_no integer NOT NULL DEFAULT 0,
  accepted_addons ARRAY,
  product_ids ARRAY,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_root_quote_id_fkey FOREIGN KEY (root_quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quotes_parent_quote_id_fkey FOREIGN KEY (parent_quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_master(id),
  CONSTRAINT quotes_crm_card_id_fkey FOREIGN KEY (crm_card_id) REFERENCES public.crm_cards(id),
  CONSTRAINT quotes_accepted_sku_fkey FOREIGN KEY (accepted_sku) REFERENCES public.product_catalog_service(sku),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.quote_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  option_sku text NOT NULL,
  sku_id text NOT NULL,
  line_kind text NOT NULL CHECK (line_kind = ANY (ARRAY['package'::text, 'setup'::text, 'addon'::text])),
  qty numeric NOT NULL DEFAULT 1,
  unit_price numeric,
  total numeric,
  commission_rate numeric,
  min_fee numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  billing text,
  pricing_model text,
  product_name text,
  description text,
  CONSTRAINT quote_lines_pkey PRIMARY KEY (id),
  CONSTRAINT quote_lines_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_lines_option_sku_fkey FOREIGN KEY (option_sku) REFERENCES public.product_catalog_service(sku),
  CONSTRAINT quote_lines_sku_id_fkey FOREIGN KEY (sku_id) REFERENCES public.product_catalog_service(sku)
);
CREATE TABLE public.invoice_hplus (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_no text NOT NULL UNIQUE,
  run_no integer NOT NULL,
  client_hotel_id text NOT NULL,
  period date NOT NULL CHECK (period = date_trunc('month'::text, period::timestamp with time zone)::date),
  client_hotel_name text,
  customer_id uuid,
  tax_id text,
  branch_code text,
  registered_name text,
  address text,
  lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  revenue numeric,
  h_comm numeric,
  compensation numeric NOT NULL DEFAULT 0,
  registration text,
  service_total numeric NOT NULL DEFAULT 0,
  discount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  vat numeric NOT NULL DEFAULT 0,
  wht numeric NOT NULL DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  payment_link_id text,
  payment_link_url text,
  payment_status text,
  paid_at timestamp with time zone,
  paid_amount numeric,
  payment_id text,
  payment_result text,
  approved_at timestamp with time zone,
  approved_by text,
  cancelled_at timestamp with time zone,
  cancelled_by text,
  cancel_reason text,
  ref1 text,
  ref2 text,
  due_date date,
  receipt_sent_at timestamp with time zone,
  receipt_sent_to text,
  receipt_sent_by text,
  cancel_requested_at timestamp with time zone,
  cancel_requested_by text,
  cancel_declined_at timestamp with time zone,
  cancel_declined_by text,
  invoice_sent_at timestamp with time zone,
  invoice_sent_to text,
  invoice_sent_by text,
  CONSTRAINT invoice_hplus_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_hplus_client_hotel_id_fkey FOREIGN KEY (client_hotel_id) REFERENCES public.hotel_profiles(client_hotel_id),
  CONSTRAINT invoice_hplus_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_master(id)
);
CREATE TABLE public.quote_share_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL UNIQUE,
  token text NOT NULL UNIQUE,
  otp_code text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quote_share_links_pkey PRIMARY KEY (id),
  CONSTRAINT quote_share_links_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  event text NOT NULL CHECK (event = ANY (ARRAY['otp_verified'::text, 'otp_failed'::text])),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quote_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT quote_access_logs_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.hpulse_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel_id text NOT NULL UNIQUE CHECK (hotel_id ~ '^Pulse-[0-9]{4}-[0-9]{4}$'::text),
  hotel_name text NOT NULL,
  province text NOT NULL,
  owner_profile_id uuid,
  prospect_status text NOT NULL DEFAULT 'new'::text CHECK (prospect_status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'meeting'::text, 'won'::text, 'lost'::text])),
  pipedrive_url text,
  unlock_policy text NOT NULL DEFAULT 'scheduled_full_unlock'::text CHECK (unlock_policy = ANY (ARRAY['scheduled_full_unlock'::text, 'preview_until_meeting'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'nurture_complete'::text, 'archived'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  pipedrive_org_id bigint,
  pipedrive_deal_id bigint,
  pipedrive_deal_title text,
  pipedrive_deal_status text,
  pipedrive_deal_url text,
  pipedrive_deal_synced_at timestamp with time zone,
  internal_notes text,
  prospect_updated_at timestamp with time zone,
  CONSTRAINT hpulse_projects_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_projects_owner_profile_id_fkey FOREIGN KEY (owner_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT hpulse_projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hpulse_project_hotels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  hotel_role text NOT NULL CHECK (hotel_role = ANY (ARRAY['target'::text, 'competitor'::text])),
  competitor_position smallint,
  hotel_name text NOT NULL,
  province text NOT NULL,
  facebook_url text,
  tiktok_handle text,
  ota_urls jsonb NOT NULL DEFAULT '{}'::jsonb,
  verified_urls jsonb NOT NULL DEFAULT '{}'::jsonb,
  identity_status text NOT NULL DEFAULT 'unverified'::text CHECK (identity_status = ANY (ARRAY['unverified'::text, 'candidates'::text, 'verified'::text, 'needs_review'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hpulse_project_hotels_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_project_hotels_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.hpulse_projects(id)
);
CREATE TABLE public.hpulse_report_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  report_id text NOT NULL UNIQUE CHECK (report_id ~ '^Pulse-[0-9]{4}-[0-9]{4}-R[0-9]{2,}$'::text),
  run_number integer NOT NULL CHECK (run_number > 0),
  check_in_date date,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'queued'::text, 'running'::text, 'review'::text, 'approved'::text, 'delivery_active'::text, 'complete'::text, 'failed'::text, 'archived'::text])),
  sections_ready smallint NOT NULL DEFAULT 0 CHECK (sections_ready >= 0 AND sections_ready <= 8),
  sections_approved smallint NOT NULL DEFAULT 0 CHECK (sections_approved >= 0 AND sections_approved <= 8),
  sections_sent smallint NOT NULL DEFAULT 0 CHECK (sections_sent >= 0 AND sections_sent <= 8),
  sections_unlocked smallint NOT NULL DEFAULT 1 CHECK (sections_unlocked >= 0 AND sections_unlocked <= 8),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hpulse_report_runs_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_report_runs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.hpulse_projects(id),
  CONSTRAINT hpulse_report_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hpulse_section_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_run_id uuid NOT NULL,
  section_code text NOT NULL CHECK (section_code = ANY (ARRAY['S01'::text, 'S02'::text, 'S03'::text, 'S04'::text, 'S05'::text, 'S06'::text, 'S07'::text, 'S08'::text])),
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'review'::text, 'approved'::text, 'partial'::text, 'waiting_input'::text, 'failed'::text])),
  approved_version_id uuid,
  locked boolean NOT NULL DEFAULT true,
  unlocked_at timestamp with time zone,
  last_error text,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hpulse_section_runs_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_section_runs_approved_version_id_fkey FOREIGN KEY (approved_version_id) REFERENCES public.hpulse_section_versions(id),
  CONSTRAINT hpulse_section_runs_report_run_id_fkey FOREIGN KEY (report_run_id) REFERENCES public.hpulse_report_runs(id)
);
CREATE TABLE public.hpulse_section_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section_run_id uuid NOT NULL,
  version_number integer NOT NULL CHECK (version_number > 0),
  version_kind text NOT NULL DEFAULT 'scraped'::text CHECK (version_kind = ANY (ARRAY['scraped'::text, 'admin_edited'::text])),
  quality_status text NOT NULL DEFAULT 'needs_review'::text CHECK (quality_status = ANY (ARRAY['complete'::text, 'partial'::text, 'missing'::text, 'needs_review'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT hpulse_section_versions_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_section_versions_section_run_id_fkey FOREIGN KEY (section_run_id) REFERENCES public.hpulse_section_runs(id),
  CONSTRAINT hpulse_section_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT hpulse_section_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hpulse_source_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section_version_id uuid NOT NULL,
  project_hotel_id uuid,
  provider text NOT NULL,
  source_url text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  verification_status text NOT NULL DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'verified'::text, 'rejected'::text, 'needs_review'::text])),
  fetched_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hpulse_source_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_source_snapshots_section_version_id_fkey FOREIGN KEY (section_version_id) REFERENCES public.hpulse_section_versions(id),
  CONSTRAINT hpulse_source_snapshots_project_hotel_id_fkey FOREIGN KEY (project_hotel_id) REFERENCES public.hpulse_project_hotels(id)
);
CREATE TABLE public.hpulse_job_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section_run_id uuid NOT NULL,
  job_group_id uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_number smallint NOT NULL CHECK (attempt_number >= 1 AND attempt_number <= 3),
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'retry_wait'::text])),
  available_at timestamp with time zone NOT NULL DEFAULT now(),
  lease_owner text,
  lease_expires_at timestamp with time zone,
  heartbeat_at timestamp with time zone,
  error_code text,
  error_message text,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hpulse_job_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_job_attempts_section_run_id_fkey FOREIGN KEY (section_run_id) REFERENCES public.hpulse_section_runs(id)
);
CREATE TABLE public.hpulse_public_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_run_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  token_hint text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_accessed_at timestamp with time zone,
  revoked_at timestamp with time zone,
  CONSTRAINT hpulse_public_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT hpulse_public_tokens_report_run_id_fkey FOREIGN KEY (report_run_id) REFERENCES public.hpulse_report_runs(id),
  CONSTRAINT hpulse_public_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);